version: '3.4'

services:
  books.api:
    image: ${DOCKER_REGISTRY-}booksapi
    build:
      context: .
      dockerfile: Books.API/Dockerfile
    ports:
    - "80:80"
  sql:
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=Pa55w0rd
    ports:
    - "1433:1433"